name: my-application

# Service 1: Database

services:
  database:
    image: postgres:15-alpine
    container_name: app-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: my-app
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: $(DB_PASSWORD)
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d my-app"]
      interval: 10s
      timeout: 5s
      retries: 5

# Service 2: Redis Cache
  cache: 
    image: redis:7-alpine
    container_name: app-cache
    restart: unless-stopped
    networks:
      - backend

# Service 3: Node.js app
  app:
    image: devopsforjesus/devops-demo:v1.0.0
    container_name: vincet-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://appuser:${DB_PASSWORD}@database:5432/my-app
      REDIS_URL: redis://cache:6379
    volumes:
      - ./src:/app/src
    depends_on:
      database:
        condition: service_healthy 
    networks:
      - frontend
      - backend

volumes:
  postgres-data:

networks:
  frontend:
  backend:

